[project]
org-name= "sachini"
version= "0.1.0"

[build-options]
observability-included=true

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    path = "./src/cosmos-db/javalibs/TokenGenerate-1.0-SNAPSHOT.jar"
    modules = ["cosmos-db"]